#ScenicView properties
#Tue Feb 24 21:09:52 OMST 2026
autoRefreshStyleSheets=false
automaticScenegraphStructureRefreshing=true
collapseContainerControls=false
collapseControls=true
ignoreMouseTransparentNodes=true
registerShortcuts=true
showBaseline=false
showBounds=true
showFilteredNodesInTree=true
showInvisibleNodes=false
showNodesIdInTree=false
showSearchBar=true
