#ScenicView properties
#Tue Feb 24 21:35:48 OMST 2026
autoRefreshStyleSheets=false
automaticScenegraphStructureRefreshing=true
collapseContainerControls=false
collapseControls=true
ignoreMouseTransparentNodes=true
registerShortcuts=true
showBaseline=false
showBounds=true
showCSSProperties=false
showDefaultProperties=true
showFilteredNodesInTree=true
showInvisibleNodes=false
showNodesIdInTree=false
showSearchBar=true
splitPaneDividerPosition=0.38350419384902146
stageHeight=800.0
stageWidth=1073.0
